### ISSUE TITLE
Publish to local Docker

### ISSUE THREAD

**Issue by rainersigwald** [rainersigwald/containers#19]
While we want things to work if you don't have Docker installed, as an inner dev loop scenario folks will surely want "make it super easy to run the thing I just built", so we should have a "publish to local Docker" option.

The only way I currently see to do this is via [`docker load`](https://docs.docker.com/engine/reference/commandline/load/), which takes as input a tarball in the format produced by [`docker export`](https://docs.docker.com/engine/reference/commandline/export/), which doesn't appear to be documented but is basically hash-named objects in a tarball.

[Jib has this](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#build-to-docker-daemon) and mentions that it requires installed Docker, so I suspect they're doing the same thing.

Questions:

* What happens if the tarball doesn't have the the base layer tarballs inside it? Do we have to download them so we can produce the tarball?
* Is there any other way to do this?
* Should we expose this tarball as an artifact, or create it transiently in memory and stream it to `docker load`?

**Comment by baronfel** [comment]
We'll need this in order for folks to have any kind of success with our initial previews, so adding it to the preview7 milestone.
