### ISSUE TITLE
Story: End-to-end initial preview

### ISSUE THREAD

**Issue by rainersigwald** [rainersigwald/containers#23]
- [x] SDK work
  - [x] https://github.com/dotnet/sdk/pull/26506
- [x] Build task assembly rainersigwald/containers#21
- [x] Pack into NuGet package that integrates task + library + targets
- [x] Hook targets into PublishProfile
- [x] Draft of inputs/targets
- [x] #19

**Comment by rainersigwald** [comment]
@baronfel What level of auth support do you think we need for the initial preview? Only no-auth/local registry, as I've got working now? Support ACR?

Or alternately prioritize the publish-to-local-Docker experience #19?

**Comment by BenVillalobos** [comment]
Build Task Assembly done: https://github.com/rainersigwald/containers/pull/41

Pack into nuget package done: https://github.com/rainersigwald/containers/pull/42/

Hook into publish profile was completed with: https://github.com/dotnet/sdk/pull/26506

**Comment by baronfel** [comment]
awesome work! all we have to do is have a good answer for the local docker story and we can kick the tires on this thing :)

**Comment by baronfel** [comment]
All our initial points have been hit! Great job, team.
