### ISSUE TITLE
Test the `UseAppHost =false` scenario

### ISSUE THREAD

**Issue by BenVillalobos** [rainersigwald/containers#64]
This should start the container with `dotnet <targetfile>`

**Comment by baronfel** [comment]
Tested this just now, and it fails. The entrypoint that we write to the container manifest looks like:

```json
"Entrypoint": [
    "dotnet container-app-dos.dll"
]
```

A multi-argument Entrypoint _should_ work, but it needs to be written as an array of separate string tokens.
