### ISSUE TITLE
Task: Good defaults for artifact storage

### ISSUE THREAD

**Issue by rainersigwald** [rainersigwald/containers#7]
We shouldn't require much ceremony around specifying a directory to store tarballs and so on; it should Just Work.

Ideally it would be shared across projects so multiple projects building an image on the same base wouldn't redownload it a bajillion times. But that conflicts a bit with MSBuild's model around intermediate files, so we'll have to design a solution.

The solution is probably just "take the defaults from #6".

**Comment by baronfel** [comment]
We'll need this caching ability before our initial previews, so adding this to the preview7 milestone.

**Comment by baronfel** [comment]
This is done!
